name: "Hello world"
description: "My first real add-on!"
version: "1.0.5"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  ip-address: '192.168.3.227'
  port: 1883
  client_name: 'Test Client'
schema:
  ip-address: str
  port: port
  client_name: str
